import React, { useMemo, useState } from "react";
import { Select, Switch } from "@douyinfe/semi-ui";
import WKApp, { ThemeMode } from "../../App";
import { updateUserLanguagePreference } from "../../Service/UserLanguageService";
import { i18n, t } from "../../i18n";
import { Locale } from "../../i18n/types";
import { NotificationUtil } from "../../Utils/NotificationUtil";
import WKModal from "../WKModal";
import "./SettingsCenter.css";

export type SettingsCenterCapability = "desktop" | "account";
export interface SettingsCenterProps {
  visible: boolean;
  isDesktop?: boolean;
  hasAccountCenter?: boolean;
  onClose: () => void;
  onSpaceManagement?: () => void;
  onLogout?: () => void;
  onSecrets?: () => void;
  onVoice?: () => void;
  onAbout?: () => void;
}
type SettingsItem = { id: string; label: string; capabilities?: SettingsCenterCapability[] };
type SettingsGroup = { title: string; items: SettingsItem[] };
const groups: SettingsGroup[] = [
  { title: "设置", items: [{ id: "general", label: "通用" }, { id: "account", label: "账号与安全", capabilities: ["account"] }, { id: "notifications", label: "通知与声音" }, { id: "voice", label: "语音输入" }] },
  { title: "桌面应用", items: [{ id: "desktop-behavior", label: "应用行为", capabilities: ["desktop"] }, { id: "downloads", label: "文件与下载", capabilities: ["desktop"] }] },
  { title: "工具与资源", items: [{ id: "shortcuts", label: "键盘快捷键" }, { id: "devices", label: "在其他设备上使用 Octo" }, { id: "about", label: "帮助与关于" }] },
];
function SettingsIcon({ name }: { name: string }) { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={name === "account" ? "M12 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm-6 8a6 6 0 0 1 12 0" : name === "notifications" ? "M18 9a6 6 0 0 0-12 0c0 7-3 7-3 8h18c0-1-3-1-3-8ZM10 21h4" : "M12 3v2m0 14v2M3 12h2m14 0h2M5.6 5.6l1.4 1.4m10 10 1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"} /></svg>; }
export function SettingsRow({ title, description, trailing, children }: { title: string; description?: string; trailing?: React.ReactNode; children?: React.ReactNode }) { return <div className="wk-settings-center__row"><div className="wk-settings-center__row-main"><div className="wk-settings-center__row-title">{title}</div>{description && <div className="wk-settings-center__row-description">{description}</div>}</div>{children ?? trailing}</div>; }
function SettingsPage({ item, onSecrets, onVoice, onAbout }: { item?: SettingsItem; onSecrets?: () => void; onVoice?: () => void; onAbout?: () => void }) {
  if (item?.id === "general") return <SettingsPageFrame title="通用" description="管理你的语言和界面外观"><SettingsRow title="界面语言" description={`当前：${i18n.getLocale() === "zh-CN" ? "简体中文" : "English"}`} trailing={<Select aria-label="界面语言" value={i18n.getLocale()} onChange={(value) => { const locale = String(value) as Locale; i18n.setLocale(locale); if (WKApp.shared.isLogined()) void updateUserLanguagePreference(locale); }} optionList={[{ value: "zh-CN", label: "简体中文" }, { value: "en-US", label: "English" }]} />} /><SettingsRow title="深色模式" description="切换后仅改变当前设备的界面配色" trailing={<Switch checked={WKApp.config.themeMode === ThemeMode.dark} onChange={(checked) => { WKApp.config.themeMode = checked ? ThemeMode.dark : ThemeMode.light; }} aria-label="深色模式" />} /></SettingsPageFrame>;
  if (item?.id === "account") return <SettingsPageFrame title="账号与安全" description="查看账号资料和安全设置"><SettingsRow title="姓名" description={WKApp.loginInfo.name || "未设置"} /><SettingsRow title="Octo 号" description={WKApp.loginInfo.shortNo || "未设置"} /><SettingsRow title="密钥管理" description="列表不显示密钥明文" trailing={<button type="button" className="wk-settings-center__link" onClick={onSecrets}>管理</button>} /></SettingsPageFrame>;
  if (item?.id === "notifications") return <SettingsPageFrame title="通知与声音" description="管理通知状态和系统权限"><SettingsRow title="桌面通知" description={WKApp.shared.notificationIsClose ? "已关闭" : "已开启"} trailing={<Switch checked={!WKApp.shared.notificationIsClose} onChange={() => { WKApp.shared.notificationIsClose = !WKApp.shared.notificationIsClose; }} aria-label="桌面通知" />} /><SettingsRow title="系统通知权限" description={typeof Notification === "undefined" ? "当前环境不支持" : Notification.permission === "granted" ? "已允许" : "未授权"} trailing={typeof Notification !== "undefined" && Notification.permission !== "granted" ? <button type="button" className="wk-settings-center__link" onClick={() => { void NotificationUtil.getInstance().requestPermission(); }}>授权</button> : undefined} /></SettingsPageFrame>;
  if (item?.id === "voice") return <SettingsPageFrame title="语音输入" description="复用现有语音输入设置"><SettingsRow title="语音输入设置" description="沿用当前 Space 语音配置和保存逻辑" trailing={<button type="button" className="wk-settings-center__link" onClick={onVoice}>打开</button>} /></SettingsPageFrame>;
  if (item?.id === "shortcuts") return <SettingsPageFrame title="键盘快捷键" description="只读查看当前客户端快捷键"><div className="wk-settings-center__shortcut-catalog"><section className="wk-settings-center__shortcut-group"><h3>聊天</h3><ShortcutRow label="新聊天" keys={["Ctrl", "N"]} /><ShortcutRow label="快速聊天" keys={["Ctrl", "Alt", "N"]} /><ShortcutRow label="归档聊天" keys={["Ctrl", "Shift", "A"]} /></section><section className="wk-settings-center__shortcut-group"><h3>导航</h3><ShortcutRow label="查找" keys={["Ctrl", "F"]} /><ShortcutRow label="返回" keys={["Alt", "←"]} /><ShortcutRow label="前进" keys={["Alt", "→"]} /></section><section className="wk-settings-center__shortcut-group"><h3>语音输入</h3><ShortcutRow label="按住说话" keys={["Ctrl", "Shift", "Space"]} /><ShortcutRow label="取消语音输入" keys={["Esc"]} /></section></div></SettingsPageFrame>;
  if (item?.id === "devices") return <SettingsPageFrame title="在其他设备上使用 Octo" description="仅展示已确认地址或状态的资源"><div className="wk-settings-center__resource-sections"><ResourceSection title="移动端"><ResourceCard title="Android" description="Android 最新版本" status="已确认下载地址" action={<a className="wk-settings-center__resource-action" href="https://github.com/Mininglamp-OSS/octo-android/releases/latest" target="_blank" rel="noreferrer">从 GitHub 下载</a>} /><ResourceCard title="iPhone" description="iOS 客户端" status="等待 App Store 上架" /></ResourceSection><ResourceSection title="开源项目"><ResourceCard title="OctoASR" description="语音识别开源项目" status="已确认项目地址" action={<a className="wk-settings-center__resource-action" href="https://github.com/Mininglamp-AI/OctoASR" target="_blank" rel="noreferrer">查看项目</a>} /></ResourceSection><ResourceSection title="桌面端"><ResourceCard title="Windows / macOS" description="桌面客户端" status="下载入口暂未确认" /></ResourceSection></div></SettingsPageFrame>;
  if (item?.id === "about") return <SettingsPageFrame title="帮助与关于" description={`当前版本 ${WKApp.config.appVersion}`}><SettingsRow title="更新检查" description="复用现有版本检查和更新日志能力" trailing={<button type="button" className="wk-settings-center__link" onClick={onAbout}>检查</button>} /><SettingsRow title="更新日志" description="查看当前版本更新内容" /></SettingsPageFrame>;
  return <SettingsPageFrame title={item?.label || "设置"} description="管理你的 Octo 使用偏好"><SettingsRow title="设置项" description="更多设置将在后续阶段接入。" /></SettingsPageFrame>;
}
function SettingsPageFrame({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="wk-settings-center__page"><header className="wk-settings-center__page-header"><h2>{title}</h2><p>{description}</p></header><section className="wk-settings-center__section-content">{children}</section></div>; }
function ShortcutRow({ label, keys }: { label: string; keys: string[] }) { return <div className="wk-settings-center__shortcut-row"><span>{label}</span><span className="wk-settings-center__shortcut-keys">{keys.map((key) => <kbd key={key}>{key}</kbd>)}</span></div>; }
function ResourceSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="wk-settings-center__resource-section"><h3>{title}</h3><div className="wk-settings-center__resource-grid">{children}</div></section>; }
function ResourceCard({ title, description, status, action }: { title: string; description: string; status: string; action?: React.ReactNode }) { return <article className="wk-settings-center__resource-card"><div><h4>{title}</h4><p>{description}</p></div><span className="wk-settings-center__resource-status">{status}</span>{action && <div>{action}</div>}</article>; }
export default function SettingsCenter({ visible, isDesktop = false, hasAccountCenter = false, onClose, onSpaceManagement, onLogout, onSecrets, onVoice, onAbout }: SettingsCenterProps) {
  const availableGroups = useMemo(() => groups.map((group) => ({ ...group, items: group.items.filter((item) => (item.capabilities ?? []).every((capability) => capability === "desktop" ? isDesktop : hasAccountCenter)) })).filter((group) => group.items.length > 0), [hasAccountCenter, isDesktop]);
  const [selectedId, setSelectedId] = useState("general");
  const selected = availableGroups.flatMap((group) => group.items).find((item) => item.id === selectedId) ?? availableGroups[0]?.items[0];
  return <WKModal visible={visible} onCancel={onClose} title={null} width="min(1080px, calc(100vw - 48px))" className="wk-settings-center-modal" bodyStyle={{ padding: 0 }} options={{ maskClosable: true }}><div className="wk-settings-center" data-testid="settings-center"><aside className="wk-settings-center__sidebar" aria-label={t("base.navRail.settingsCenter.navigation")}><h1>设置</h1><nav className="wk-settings-center__navigation">{availableGroups.map((group) => <section className="wk-settings-center__group" key={group.title}><h2>{group.title}</h2><div className="wk-settings-center__nav-list">{group.items.map((item) => <button type="button" key={item.id} data-testid={`settings-center-nav-${item.id}`} className={`wk-settings-center__nav-item${selected?.id === item.id ? " is-active" : ""}`} aria-current={selected?.id === item.id ? "page" : undefined} onClick={() => setSelectedId(item.id)}><SettingsIcon name={item.id} /><span>{item.label}</span></button>)}</div></section>)}</nav><div className="wk-settings-center__footer">{onSpaceManagement && <button type="button" data-testid="settings-center-space-management" onClick={onSpaceManagement}>⌘ {t("base.navRail.settingsPanel.spaceManagement")}</button>}{onLogout && <button type="button" className="is-danger" data-testid="settings-center-logout" onClick={onLogout}>↪ {t("base.navRail.settingsPanel.logout")}</button>}</div></aside><main className="wk-settings-center__content" data-testid="settings-center-content"><button type="button" className="wk-settings-center__close" aria-label={t("base.common.close")} onClick={onClose}>×</button><SettingsPage item={selected} onSecrets={onSecrets} onVoice={onVoice} onAbout={onAbout} /></main></div></WKModal>;
}
