import React from "react";
import { Select, Switch } from "@douyinfe/semi-ui";
import WKApp, { ThemeMode } from "../../App";
import { updateUserLanguagePreference } from "../../Service/UserLanguageService";
import { i18n, t } from "../../i18n";
import { Locale } from "../../i18n/types";
import { NotificationUtil } from "../../Utils/NotificationUtil";
import type { SettingsItem } from "./settingsRegistry";
import { createNotificationAdapter } from "../../Runtime/adapters";

export function SettingsRow({ title, description, trailing, children }: { title: string; description?: string; trailing?: React.ReactNode; children?: React.ReactNode }) { return <div className="wk-settings-center__row"><div className="wk-settings-center__row-main"><div className="wk-settings-center__row-title">{title}</div>{description && <div className="wk-settings-center__row-description">{description}</div>}</div>{children ?? trailing}</div>; }

export function SettingsPage({ item, environment, onSecrets, onVoice, onAbout }: { item?: SettingsItem; environment: import("../../Runtime").RuntimeEnvironment; onSecrets?: () => void; onVoice?: () => void; onAbout?: () => void }) {
  if (item?.id === "general") return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.general.title")} description={t("base.navRail.settingsCenter.page.general.description")}><SettingsRow title={t("base.navRail.settingsCenter.row.language")} description={t("base.navRail.settingsCenter.row.currentLanguage", { language: i18n.getLocale() === "zh-CN" ? t("base.navRail.settingsCenter.language.zh") : t("base.navRail.settingsCenter.language.en") })} trailing={<Select aria-label={t("base.navRail.settingsCenter.row.language")} value={i18n.getLocale()} onChange={(value) => { const locale = String(value) as Locale; i18n.setLocale(locale); if (WKApp.shared.isLogined()) void updateUserLanguagePreference(locale); }} optionList={[{ value: "zh-CN", label: t("base.navRail.settingsCenter.language.zh") }, { value: "en-US", label: t("base.navRail.settingsCenter.language.en") }]} />} /><SettingsRow title={t("base.navRail.settingsCenter.row.darkMode")} description={t("base.navRail.settingsCenter.row.darkModeDescription")} trailing={<Switch checked={WKApp.config.themeMode === ThemeMode.dark} onChange={(checked) => { WKApp.config.themeMode = checked ? ThemeMode.dark : ThemeMode.light; }} aria-label={t("base.navRail.settingsCenter.row.darkMode")} />} /></SettingsPageFrame>;
  if (item?.id === "account") return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.account.title")} description={t("base.navRail.settingsCenter.page.account.description")}><SettingsRow title={t("base.navRail.settingsCenter.row.name")} description={WKApp.loginInfo.name || t("base.navRail.settingsCenter.value.unset")} /><SettingsRow title={t("base.navRail.settingsCenter.row.octoNo")} description={WKApp.loginInfo.shortNo || t("base.navRail.settingsCenter.value.unset")} /><SettingsRow title={t("base.navRail.settingsCenter.row.secrets")} description={t("base.navRail.settingsCenter.row.secretsDescription")} trailing={<button type="button" className="wk-settings-center__link" onClick={onSecrets}>{t("base.navRail.settingsCenter.action.manage")}</button>} /></SettingsPageFrame>;
  if (item?.id === "notifications") {
    const notificationAdapter = createNotificationAdapter(environment);
    return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.notifications.title")} description={t("base.navRail.settingsCenter.page.notifications.description")}><SettingsRow title={t("base.navRail.settingsCenter.row.desktopNotifications")} description={WKApp.shared.notificationIsClose ? t("base.navRail.settingsCenter.value.off") : t("base.navRail.settingsCenter.value.on")} trailing={<Switch checked={!WKApp.shared.notificationIsClose} onChange={() => { WKApp.shared.notificationIsClose = !WKApp.shared.notificationIsClose; }} aria-label={t("base.navRail.settingsCenter.row.desktopNotifications")} />} /><SettingsRow title={t("base.navRail.settingsCenter.row.systemPermission")} description={notificationAdapter.getPermission()} trailing={notificationAdapter.getPermission() === "default" ? <button type="button" className="wk-settings-center__link" onClick={() => { void notificationAdapter.requestPermission(); }}>{t("base.navRail.settingsCenter.action.authorize")}</button> : undefined} /></SettingsPageFrame>;
  }
  if (item?.id === "voice") return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.voice.title")} description={t("base.navRail.settingsCenter.page.voice.description")}><SettingsRow title={t("base.navRail.settingsCenter.row.voice")} description={t("base.navRail.settingsCenter.row.voiceDescription")} trailing={<button type="button" className="wk-settings-center__link" onClick={onVoice}>{t("base.navRail.settingsCenter.action.open")}</button>} /></SettingsPageFrame>;
  if (item?.id === "shortcuts") return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.shortcuts.title")} description={t("base.navRail.settingsCenter.page.shortcuts.description")}><div className="wk-settings-center__shortcut-catalog"><section className="wk-settings-center__shortcut-group"><h3>{t("base.navRail.settingsCenter.shortcut.chat")}</h3><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.newChat")} keys={["Ctrl", "N"]} /><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.quickChat")} keys={["Ctrl", "Alt", "N"]} /><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.archiveChat")} keys={["Ctrl", "Shift", "A"]} /></section><section className="wk-settings-center__shortcut-group"><h3>{t("base.navRail.settingsCenter.shortcut.navigation")}</h3><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.search")} keys={["Ctrl", "F"]} /><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.back")} keys={["Alt", "←"]} /><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.forward")} keys={["Alt", "→"]} /></section><section className="wk-settings-center__shortcut-group"><h3>{t("base.navRail.settingsCenter.shortcut.voice")}</h3><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.holdToTalk")} keys={["Ctrl", "Shift", "Space"]} /><ShortcutRow label={t("base.navRail.settingsCenter.shortcut.cancelVoice")} keys={["Esc"]} /></section></div></SettingsPageFrame>;
  if (item?.id === "devices") return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.devices.title")} description={t("base.navRail.settingsCenter.page.devices.description")}><div className="wk-settings-center__resource-sections"><ResourceSection title={t("base.navRail.settingsCenter.resource.mobile")}><ResourceCard title="Android" description={t("base.navRail.settingsCenter.resource.androidDescription")} status={t("base.navRail.settingsCenter.resource.downloadConfirmed")} action={<a className="wk-settings-center__resource-action" href="https://github.com/Mininglamp-OSS/octo-android/releases/latest" target="_blank" rel="noreferrer">{t("base.navRail.settingsCenter.action.download")}</a>} /><ResourceCard title="iPhone" description={t("base.navRail.settingsCenter.resource.iosDescription")} status={t("base.navRail.settingsCenter.resource.appStorePending")} /></ResourceSection><ResourceSection title={t("base.navRail.settingsCenter.resource.openSource")}><ResourceCard title="OctoASR" description={t("base.navRail.settingsCenter.resource.asrDescription")} status={t("base.navRail.settingsCenter.resource.projectConfirmed")} action={<a className="wk-settings-center__resource-action" href="https://github.com/Mininglamp-AI/OctoASR" target="_blank" rel="noreferrer">{t("base.navRail.settingsCenter.action.viewProject")}</a>} /></ResourceSection><ResourceSection title={t("base.navRail.settingsCenter.resource.desktop")}><ResourceCard title="Windows / macOS" description={t("base.navRail.settingsCenter.resource.desktopDescription")} status={t("base.navRail.settingsCenter.resource.downloadPending")} /></ResourceSection></div></SettingsPageFrame>;
  if (item?.id === "about") return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.about.title")} description={t("base.navRail.settingsCenter.page.about.versionPrefix") + " " + WKApp.config.appVersion}><SettingsRow title={t("base.navRail.settingsCenter.row.updateCheck")} description={t("base.navRail.settingsCenter.row.updateCheckDescription")} trailing={<button type="button" className="wk-settings-center__link" onClick={onAbout}>{t("base.navRail.settingsCenter.action.check")}</button>} /><SettingsRow title={t("base.navRail.settingsCenter.row.changelog")} description={t("base.navRail.settingsCenter.row.changelogDescription")} /></SettingsPageFrame>;
  return <SettingsPageFrame title={t("base.navRail.settingsCenter.page.fallback.title")} description={t("base.navRail.settingsCenter.page.fallback.description")}><SettingsRow title={t("base.navRail.settingsCenter.row.placeholder")} description={t("base.navRail.settingsCenter.placeholder")} /></SettingsPageFrame>;
}
function SettingsPageFrame({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="wk-settings-center__page"><header className="wk-settings-center__page-header"><h2>{title}</h2><p>{description}</p></header><section className="wk-settings-center__section-content">{children}</section></div>; }
function ShortcutRow({ label, keys }: { label: string; keys: string[] }) { return <div className="wk-settings-center__shortcut-row"><span>{label}</span><span className="wk-settings-center__shortcut-keys">{keys.map((key) => <kbd key={key}>{key}</kbd>)}</span></div>; }
function ResourceSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="wk-settings-center__resource-section"><h3>{title}</h3><div className="wk-settings-center__resource-grid">{children}</div></section>; }
function ResourceCard({ title, description, status, action }: { title: string; description: string; status: string; action?: React.ReactNode }) { return <article className="wk-settings-center__resource-card"><div><h4>{title}</h4><p>{description}</p></div><span className="wk-settings-center__resource-status">{status}</span>{action && <div>{action}</div>}</article>; }
